name: Simple Action on Push

on:
  push:
    branches:
      - main  # You can change this to any branch name

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print a Message
        run: |
          echo "Push event triggered! This is just a test message."
